CREATE TABLE COOKBOOK(
	Title			TEXT		NOT NULL,
	Author			TEXT		NOT NULL,
	ID				INT					IDENTITY(1,1),
	-- PK
	CONSTRAINT		COOKBOOK_PK			PRIMARY KEY(ID)
);


CREATE TABLE RECIPE(
	Name			TEXT		NOT NULL,
	Directions		TEXT		NOT NULL,
	ID				INT					IDENTITY(1,1),
	CookbookID		INT					NOT NULL,
	-- PK
	CONSTRAINT		RECIPE_FK			PRIMARY KEY(ID),
	-- FK
	CONSTRAINT		COOKBOOK_FK			FOREIGN KEY(CookbookID)
					REFERENCES COOKBOOK(ID)
					ON DELETE CASCADE
					ON UPDATE CASCADE
);


CREATE TABLE INGREDIENT(
	Name			TEXT		NOT NULL,
	ID				INT					IDENTITY(1,1),
	-- PK
	CONSTRAINT		INGREDIENT_PK		PRIMARY KEY(ID)
);


CREATE TABLE INGREDIENTLINE(
	RecipeID		INT					NOT NULL,
	IngredientID	INT					NOT NULL,
	Quantity		REAL        		NOT NULL,
	Unit			TEXT    		    NOT NULL,
	ID				INT					IDENTITY(1,1),
	-- PK
	CONSTRAINT		ILine_PK			PRIMARY KEY(ID),
	-- FK
	CONSTRAINT		INGRIDIENT_FK		FOREIGN KEY(IngredientID)
					REFERENCES INGREDIENT(ID)
					ON DELETE CASCADE
					ON UPDATE CASCADE,

	CONSTRAINT		RECIPEL_FK			FOREIGN KEY(RecipeID)
					REFERENCES RECIPE(ID)
					ON DELETE CASCADE
					ON UPDATE CASCADE
);