INSERT INTO COOKBOOK VALUES('Opskrifter', 'Nikolaj Lauridsen');

INSERT INTO RECIPE VALUES('Pandekager', 'Bland og steg', 1);

INSERT INTO INGREDIENT VALUES('Æg');
INSERT INTO INGREDIENT VALUES('Mel');
INSERT INTO INGREDIENT VALUES('Mælk');
INSERT INTO INGREDIENT VALUES('Olie');
INSERT INTO INGREDIENT VALUES('Sukker');

INSERT INTO INGREDIENTLINE VALUES(1,1,4,'stk');
INSERT INTO INGREDIENTLINE VALUES(1,2,400,'gr');
INSERT INTO INGREDIENTLINE VALUES(1,3,4,'dl');
INSERT INTO INGREDIENTLINE VALUES(1,4,2,'tsk');
INSERT INTO INGREDIENTLINE VALUES(1,5,2,'spsk');